### ISSUE TITLE
Live demo with RealSense D435 camera

### ISSUE THREAD

**Issue by mhaboali** [hassony2/handobjectconsist#1]
Hi, thanks for sharing this great project!

I'm wondering if it's possible to run a live demo using the D435i camera or this library works only with specific datasets?

Thanks!

**Comment by hassony2** [comment]
Hi @mhaboali !

Currently the models only work on the specific datasets (note that object pose estimation is instance-specific in our case, so the model needs to see the CAD model of the object at train time).
For results on a new dataset you might be interested in our previous work https://github.com/hassony2/obman_train (you can try the video demo)

Cheers !

Yana
