### ISSUE TITLE
What do you mean by "BaseQueries" and " TransQueries" in your code?

### ISSUE THREAD

**Issue by WeedsInML** [hassony2/handobjectconsist#17]
Hi  Yana~ I'm now reading your code. I am confused about these two names. And I don't know why you do some transformation on data if "TransQueries" are selected. I would be appreciate if you can explain! Thanks!

**Comment by hassony2** [comment]
Hi !

BaseQueries refer to all values *before* data-augmentation, while TransQueries refer to values associated to transformed images.

Hope this helps !

Best,

Yana
