### ISSUE TITLE
Why dose the cam_extr look like this?

### ISSUE THREAD

**Issue by MengHao666** [hassony2/handobjectconsist#2]
Hi,hassony.

Thanks for this work.
I start leaning th code recently, and now I got confused bout the "get_hand_verts3d" function in ho3dv2.py.
In such function, you use **cam_extr** and  it has been defined as **np.array([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])**.
I cannot know the reason. 
Hope do some little work in such field ,welcome for any generous suggestion.

**Comment by hassony2** [comment]
Hi @MengHao666 ,

Thank you for your interest in our work  !
Typically this comes from different xyz conventions. So here it means that the y and z axis are flipped :)

All the best,

Yana
