### ISSUE TITLE
Training on HO3D

### ISSUE THREAD

**Issue by zc-alexfan** [hassony2/handobjectconsist#5]
Hi Yana,

Thanks for sharing your code on GitHub. It is very cool! I am trying to reproduce your HO3D results using your code, but encountered an error and I am not sure if I missed anything.

The command for launching the training procedure:
```
python trainmeshreg.py --freeze_batchnorm --workers 8 --block_rot --train_datasets ho3dv2 --version 1
```

The error message:
```
Traceback (most recent call last):
  File "trainmeshreg.py", line 361, in <module>
    main(args)
  File "trainmeshreg.py", line 79, in main
    sample_nb=None,
  File "/home/elytra/nether/projects/handobjectconsist/meshreg/netscripts/get_dataset.py", line 40, in get_dataset
    full_sequences=False,
  File "/home/elytra/nether/projects/handobjectconsist/meshreg/datasets/ho3dv2.py", line 259, in __init__
    self.obj_meshes = ho3dfullutils.load_objects(os.path.join(self.root, "modelsprocess"))
  File "/home/elytra/nether/projects/handobjectconsist/meshreg/datasets/ho3dfullutils.py", line 8, in load_objects
    object_names = [obj_name for obj_name in os.listdir(obj_root) if ".tgz" not in obj_name]
FileNotFoundError: [Errno 2] No such file or directory: 'data/ho3dv2/modelsprocess'
```

I am not sure what `modelsprocess` is, but according to the object file names, it should be YCB object files because the file name is called `textured_simple_2000.obj` while the YCB objects are called `textured_simple.obj`.

Questions:
- How do you go from `textured_simple.obj` to `textured_simple_2000.obj`?  It is my first mesh-based project. Could you kindly provide some instructions to generate the `modelsprocess` folder? (my email is `zc.alexfan@gmail.com`)

Thank you,
Alex

**Comment by lixiny** [comment]
> Hi Yana,
> 
> Thanks for sharing your code on GitHub. It is very cool! I am trying to reproduce your HO3D results using your code, but encountered an error and I am not sure if I missed anything.
> 
> The command for launching the training procedure:
> 
> ```
> python trainmeshreg.py --freeze_batchnorm --workers 8 --block_rot --train_datasets ho3dv2 --version 1
> ```
> 
> The error message:
> 
> ```
> Traceback (most recent call last):
>   File "trainmeshreg.py", line 361, in <module>
>     main(args)
>   File "trainmeshreg.py", line 79, in main
>     sample_nb=None,
>   File "/home/elytra/nether/projects/handobjectconsist/meshreg/netscripts/get_dataset.py", line 40, in get_dataset
>     full_sequences=False,
>   File "/home/elytra/nether/projects/handobjectconsist/meshreg/datasets/ho3dv2.py", line 259, in __init__
>     self.obj_meshes = ho3dfullutils.load_objects(os.path.join(self.root, "modelsprocess"))
>   File "/home/elytra/nether/projects/handobjectconsist/meshreg/datasets/ho3dfullutils.py", line 8, in load_objects
>     object_names = [obj_name for obj_name in os.listdir(obj_root) if ".tgz" not in obj_name]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/ho3dv2/modelsprocess'
> ```
> 
> I am not sure what `modelsprocess` is, but according to the object file names, it should be YCB object files because the file name is called `textured_simple_2000.obj` while the YCB objects are called `textured_simple.obj`.
> 
> Questions:
> 
> * How do you go from `textured_simple.obj` to `textured_simple_2000.obj`?  It is my first mesh-based project. Could you kindly provide some instructions to generate the `modelsprocess` folder? (my email is `zc.alexfan@gmail.com`)
> 
> Thank you,
> Alex

HI Alex, have you solved the problem yet? 
I tried to downsample the YCB meshes using MeshLab, and adjust the average vertex number to 2000 for each object category. 
There is no FileNotFoundError during training.

**Comment by zc-alexfan** [comment]
Hi @lixiny, I haven't resolved the issue. I was waiting for @hassony2 's response. 

What object models do you use for ho3d training? Also, what's your command to launch the training?

**Comment by lixiny** [comment]
> Hi @lixiny, I haven't resolved the issue. I was waiting for @hassony2 's response.
> 
> What object models do you use for ho3d training? Also, what's your command to launch the training?

I started a new issue and  was also waiting for her response.
I downsampled the original YCB models that used in HO3D

**Comment by pgrady3** [comment]
I'm also interested in details about the models used in HO3D training. Could the author provide more details about the models used?

**Comment by hassony2** [comment]
Hi @lixiny @pgrady3 and @zc-alexfan 

I just released code and a pre-trained model on the official HO3D-v2 version as the [v0.3 release](https://github.com/hassony2/handobjectconsist/releases/tag/v0.3).
You can find updated details in the README :)


Hopefully this will be of use to you !

Best,

Yana
