### ISSUE TITLE
Training details about HO3D

### ISSUE THREAD

**Issue by lixiny** [hassony2/handobjectconsist#6]
Hi, Hasson, 

Thanks for your great work!

Could you be kind enough to share the training args when train the meshreg on HO3D dataset. 
as well as the pretrained model (of HO3D)

Thanks 👍

**Comment by hassony2** [comment]
Hi !

Could you clarify exactly which models you are referring to ?
Given that the early version of the HO3D dataset which I used for the paper is not publicly available, I do not currently plan on releasing these models. I could however  release code/models which train on the official version of their dataset and which would provide results close to the one I submitted to https://competitions.codalab.org/competitions/22485?secret_key=756c1c8c-84ec-47ec-aa17-42f1fa330fb4#results. Would that be of interest to you ?


All the best,

Yana
Best,

Yana

**Comment by lixiny** [comment]
Hi Yana, 

Thanks for your clear response. 
I noticed that the CodeLab challenge only contains metrics of hand.  (no  object corners)
I would like to ask whether you are planing to release the MeshRegNet full-trained model on  HO-3D official version. 

All the best. 


Lixin

**Comment by hassony2** [comment]
Hi @lixiny 

I just released a pre-trained model on the HO-3D official version which you can find [here](https://github.com/hassony2/handobjectconsist/releases/tag/v0.3).
You can check the updated readme for more details !

Best,

Yana
