### ISSUE TITLE
Figure 8 & Figure 7 plot data

### ISSUE THREAD

**Issue by nitba** [hassony2/handobjectconsist#8]
Hi @hassony2 ,
It would be great if you share plot data, for the fair comparison,

Thanks,

**Comment by hassony2** [comment]
Hi @Ivamcoder, 

I just pushed code which can regenerate the figures at https://github.com/hassony2/handobjectconsist/tree/master/figures.

Hope this helps !

Best,

Yana

**Comment by MengHao666** [comment]
> Hi @hassony2 ,
> It would be great if you share plot data, for the fair comparison,
> 
> Thanks,
Hi, I wonder how I could caluate the hand pose error mentioned in  Figure 5 and Figure 7. I did get the groundtruth joints 2D location in RGB image coordinate and joints 2D location reprojected by 3D joint location predicted. I couldn't find any such evaluation code in this repo.
Could u be kind to give any advice?
Thanks a lot!

**Comment by MengHao666** [comment]
> Hi @hassony2 ,
> It would be great if you share plot data, for the fair comparison,
> 
> Thanks,

@Ivamcoder Hi, I wonder how I could caluate the hand pose error mentioned in  Figure 5 and Figure 7. I did get the groundtruth joints 2D location in RGB image coordinate and joints 2D location reprojected by 3D joint location predicted. I couldn't find any such evaluation code in this repo.
Could u be kind to give any advice?
Thanks a lot!
